#
#Fri Sep 15 16:33:45 UTC 2023
PleaseCompleteTheFieldsBelow=Bitte füllen Sie die folgenden Felder aus und registrieren Sie Ihr Fahrzeug.
RegisteringYourVehicle=Registrierung Ihres Fahrzeugs
VehicleID=Fahrzeugidentifikation
VehicleDetails=Fahrzeugangaben
ReturnHome=Home
ParkingPolicyText=<p>Mitarbeitern von Workday stehen mehrere Parkmöglichkeiten zur Verfügung. Da die Parkmöglichkeiten in der Firmengarage jedoch begrenzt sind, müssen Mitarbeiter ihr Fahrzeug bei unserem System anmelden. Ein Parkplatz in der Garage kostet $50 pro Monat und ist an das Parkbüro auf dem Campus zu zahlen. <b>Die Nichteinhaltung der unten beschriebenen Richtlinie führt zum sofortigen Verlust Ihrer Parkregistrierung. Workday übernimmt keine Verantwortung für die Sicherheit Ihres Fahrzeugs.</b></p><br></br>
PleaseClickTheButtonBelow=Bitte klicken Sie auf die Schaltfläche unten, um den Registrierungsprozess zu starten.
CarDescriptionYear=<b>Jahr\:</b>
DeleteButton=Löschen
PoweredByWorkdayExtend=Bereitgestellt von<br/><b>Workday Extend</b>
DeleteRegisteredVehicle=Registriertes Fahrzeug löschen
UpdateRegistration=Registrierung aktualisieren
Home=Return to the Home Page
CarDescriptionLicensePlate=<br/><b>Nummernschild\:</b> 
DateOfRegistration=Datum der Registrierung
DeleteText=Bitte klicken Sie auf die Schaltfläche unten, um Ihre Registrierung zu löschen.
Color=Farbe
VehicleRegistration=Kfz-Zulassung
Make=Machen
RegisterVehicle=Fahrzeug registrieren
DeleteHelpText=Sind Sie sicher, dass Sie Ihre Fahrzeugregistrierung löschen möchten? Klicken Sie auf die Schaltfläche OK für Ja oder Abbrechen, um zurückzugehen.
CarDescriptionColor=<br/><b>Farbe\:</b>
LicensePlateNumber=Kfz-Kennzeichen
RegisterButton=Registrieren
IsCompact=ist kompakt?
Year=Jahr
ParkingPolicy=Parkplatzpolitik
Model=Modell
MyRegisteredVehicles=Meine zugelassenen Fahrzeuge
DeleteRegistration=Registrierung löschen
Location=Ort
AdditionalLinks=Zusätzliche links
Confirm=Bestätigen
ViewLocations=Standorte anzeigen
ViewRegistrations=Registrierungen anzeigen
KeyTasks=Hauptaufgaben
DeveloperForum=Entwicklerforum