#
#Fri Sep 15 16:33:45 UTC 2023
PleaseCompleteTheFieldsBelow=Please complete the fields below and register your vehicle.
RegisteringYourVehicle=Registering Your Vehicle
VehicleID=Vehicle ID
VehicleDetails=Vehicle Details
ReturnHome=Home
ParkingPolicyText=<p>There are several parking options available to employees at Workday. However since parking space in the company garage is limited, employees must register their vehicle with our system. A parking space in the garage costs $50 per month to be paid to the parking office on campus. <b>Failure to follow the Policy outlined below will result in immediate loss of your parking registration. Workday assumes no responsibility for your vehicle's safety.</b></p><br></br>
PleaseClickTheButtonBelow=Please click the button below to begin the registration process.
CarDescriptionYear=<b>Year\:</b> 
DeleteButton=Delete
PoweredByWorkdayExtend=Powered By<br/><b>Workday Extend</b>
DeleteRegisteredVehicle=Delete Registered Vehicle
UpdateRegistration=Update Registration
Home=Return to the Home Page
CarDescriptionLicensePlate=<br/><b>License Plate\:</b> 
DateOfRegistration=Date of Registration
DeleteText=Please click the button below to delete your registration.
Color=Color
VehicleRegistration=Vehicle Registration
Make=Make
RegisterVehicle=Register Vehicle
DeleteHelpText=Are you sure you want to delete your vehicle registration? Click the OK button for yes, or cancel to go back.
CarDescriptionColor=<br/><b>Color\:</b> 
LicensePlateNumber=License Plate Number
RegisterButton=Register
IsCompact=Is Compact?
Year=Year
ParkingPolicy=Parking Policy
Model=Model
MyRegisteredVehicles=My Registered Vehicles
DeleteRegistration=Delete Registration
Location=Location
AdditionalLinks=Additional Links
Confirm=Confirm
ViewLocations=View Locations
ViewRegistrations=All Registrations
KeyTasks=Key Tasks
DeveloperForum=Developer Forum