#
#Fri Sep 15 16:33:45 UTC 2023
PleaseCompleteTheFieldsBelow=Complete los campos a continuación y registre su vehículo.
RegisteringYourVehicle=Registro de su vehículo
VehicleID=ID del vehículo
VehicleDetails=Detalles del vehículo
ReturnHome=Hogar
ParkingPolicyText=<p>Hay varias opciones de estacionamiento disponibles para los empleados de Workday. Sin embargo, dado que el espacio de estacionamiento en el garaje de la empresa es limitado, los empleados deben registrar su vehículo en nuestro sistema. Un espacio de estacionamiento en el garaje cuesta $50 por mes a pagar a la oficina de estacionamiento en el campus. <b>El incumplimiento de la Política descrita a continuación resultará en la pérdida inmediata de su registro de estacionamiento. Workday no asume ninguna responsabilidad por la seguridad de su vehículo.</b></p><br></br>
PleaseClickTheButtonBelow=Haga clic en el botón de abajo para comenzar el proceso de registro.
CarDescriptionYear=<b>Año\:</b> 
DeleteButton=Borrar
PoweredByWorkdayExtend=Desarrollado por<br/><b>Workday Extend</b>
DeleteRegisteredVehicle=Eliminar vehículo registrado
UpdateRegistration=Actualizar registro
Home=Return to the Home Page
CarDescriptionLicensePlate=<br/><b>Matrícula\:</b> 
DateOfRegistration=Fecha de registro
DeleteText=Haga clic en el botón de abajo para eliminar su registro.
Color=Color
VehicleRegistration=Registro de Vehículo
Make=Marca
RegisterVehicle=Registrar vehículo
DeleteHelpText=¿Está seguro de que desea eliminar el registro de su vehículo? Haga clic en el botón Aceptar para sí, o cancelar para volver.
CarDescriptionColor=<br/><b>Color\:</b> 
LicensePlateNumber=Numero de licencia
RegisterButton=Registrarse
IsCompact=Es compacta
Year=Año
ParkingPolicy=Política de estacionamiento
Model=Modelo
MyRegisteredVehicles=Mis vehículos registrados
DeleteRegistration=Eliminar registro
Location=Ubicación
AdditionalLinks=Enlaces Adicionales
Confirm=Confirmar
ViewLocations=Ver ubicaciones
KeyTasks=Tareas clave
DeveloperForum=Foro de desarrolladores