#
#Fri Sep 15 16:33:45 UTC 2023
PleaseCompleteTheFieldsBelow=Veuillez remplir les champs ci-dessous et enregistrer votre véhicule.
RegisteringYourVehicle=Immatriculation de votre véhicule
VehicleID=Identification du véhicule
VehicleDetails=Les détails du véhicule
ReturnHome=Home
ParkingPolicyText=<p>Plusieurs options de stationnement sont disponibles pour les employés de Workday. Cependant, comme les places de stationnement dans le garage de l'entreprise sont limitées, les employés doivent enregistrer leur véhicule auprès de notre système. Une place de stationnement dans le garage coûte 50 $ par mois à payer au bureau du stationnement sur le campus. <b> Le non-respect de la politique décrite ci-dessous entraînera la perte immédiate de votre enregistrement de stationnement. Workday décline toute responsabilité quant à la sécurité de votre véhicule.</b></p><br></br>
PleaseClickTheButtonBelow=Veuillez cliquer sur le bouton ci-dessous pour commencer le processus d'inscription.
CarDescriptionYear=<b>Année\:</b> 
DeleteButton=Supprimer
PoweredByWorkdayExtend=Propulsé par<br/><b>Workday Extend</b>
DeleteRegisteredVehicle=Supprimer le véhicule enregistré
UpdateRegistration=Mettre à jour l'enregistrement
Home=Return to the Home Page
CarDescriptionLicensePlate=<br/><b>Plaque d'immatriculation\:</b> 
DateOfRegistration=Date d'enregistrement
DeleteText=Veuillez cliquer sur le bouton ci-dessous pour supprimer votre inscription.
Color=Couleur
VehicleRegistration=Immatriculation des véhicules
Make=Marque
RegisterVehicle=Enregistrer le véhicule
DeleteHelpText=Êtes-vous sûr de vouloir supprimer l'immatriculation de votre véhicule? Cliquez sur le bouton OK pour oui ou sur Annuler pour revenir en arrière.
CarDescriptionColor=<br/><b>Couleur\:</b> 
LicensePlateNumber=Numéro de plaque d'immatriculation
RegisterButton=Immatriculer
IsCompact=est compact
Year=An
ParkingPolicy=Politique de stationnement
Model=Modèle
MyRegisteredVehicles=Mes véhicules enregistrés
DeleteRegistration=Supprimer l'enregistrement
Location=Emplacement
AdditionalLinks=Liens supplémentaires
Confirm=Confirmer
ViewLocations=Afficher les emplacements
ViewRegistrations=Voir les inscriptions
KeyTasks=Tâches clés
DeveloperForum=Forum des développeurs