#
#Fri Sep 15 16:33:45 UTC 2023
PleaseCompleteTheFieldsBelow=以下の情報を入力し車両を登録してください。
RegisteringYourVehicle=車両の登録
VehicleID=車両ID
VehicleDetails=車両詳細
ReturnHome=ホーム
ParkingPolicyText=<p>Workdayでは従業員向けにいくつかの駐車オプションがあります。ただし、会社のガレージの駐車スペースは限られているため、従業員はシステムに車両を登録する必要があります。ガレージの駐車スペースは月額50ドルで、キャンパス内の駐車事務所に支払う必要があります。 <b>以下に記載されているポリシーに従わない場合、駐車登録が直ちに失効します。Workdayは車両の安全性に対して一切の責任を負いません。</b></p><br></br>
PleaseClickTheButtonBelow=登録プロセスを開始するには、以下のボタンをクリックしてください。
CarDescriptionYear=<b>年式\:</b> 
DeleteButton=削除
PoweredByWorkdayExtend=Powered By<br/><b>Workday Extend</b>
DeleteRegisteredVehicle=登録済み車両の削除
UpdateRegistration=登録の更新
Home=ホームページに戻る
CarDescriptionLicensePlate=<br/><b>ナンバープレート\:</b> 
DateOfRegistration=登録日
DeleteText=登録を削除するには、以下のボタンをクリックしてください。
Color=色
VehicleRegistration=車両登録
Make=メーカー
RegisterVehicle= 車両を登録する
DeleteHelpText=車両登録を削除してもよろしいですか？はいの場合はOKボタンをクリックし、キャンセルする場合は戻るをクリックしてください。
CarDescriptionColor=<br/><b>色\:</b> 
LicensePlateNumber=ナンバープレート番号
RegisterButton=登録
IsCompact=コンパクトカーか
Year=年式
ParkingPolicy=駐車ポリシー
Model=モデル
MyRegisteredVehicles=登録済み車両
DeleteRegistration=登録の削除
Location=場所
AdditionalLinks=追加のリンク
Confirm=確認する
ViewLocations=場所を表示
ViewRegistrations=登録の表示
KeyTasks=主要なタスク
DeveloperForum=開発者フォーラム