var getScatterData = function() {
  var chartData = [
    {
      "rating": "Good",
      "size": "5",
      "label": "Point 1",
      "x": -216.74,
      "y": 108.22
    },
    {
      "rating": "Bad",
      "size": "12",
      "label": "Point 2",
      "x": 54,
      "y": 82.56
    },
    {
      "rating": "Good",
      "size": "2",
      "label": "Point 3",
      "x": -16,
      "y": 16
    },
    {
      "rating": "Mediocre",
      "size": "-1",
      "label": "Point 4",
      "x": -76.5,
      "y": -104.84627
    },
    {
      "rating": "OK",
      "size": "6",
      "label": "Point 5",
      "x": 216.743,
      "y": -118.22
    },
    {
      "rating": "Mediocre",
      "size": "8",
      "label": "Point 6",
      "x": 100,
      "y": 10
    },
    {
      "rating": "Bad",
      "size": "5",
      "label": "Point 7",
      "x": -159,
      "y": 35
    }
  ]
  return chartData
}


{
  "getScatterData": getScatterData
}